"""Auto-generated SQLAlchemy model for `checkout_alternative`.

Mirrors the colorcommerce.checkout_alternative table. Edit with care — re-running the
generator may overwrite changes.
"""
from sqlalchemy import Column, Integer, String, Text
from app.database import Base


class CheckoutAlternative(Base):
    __tablename__ = "checkout_alternative"

    site_id = Column("site_id", Integer, primary_key=True)
    google_checkout = Column("google_checkout", String(1), nullable=True)
    google_merchant_id = Column("google_merchant_id", String(20), nullable=True)
    google_merchant_key = Column("google_merchant_key", String(30), nullable=True)
    google_checkout_button = Column("google_checkout_button", String(6), nullable=True)
    google_beacon_url = Column("google_beacon_url", String(255), nullable=True)
    amazon_checkout = Column("amazon_checkout", String(1), nullable=True)
    amazon_checkout_type = Column("amazon_checkout_type", String(1), nullable=True)
    amazon_merchant_id = Column("amazon_merchant_id", String(20), nullable=True)
    amazon_access_key = Column("amazon_access_key", String(20), nullable=True)
    amazon_secret_key = Column("amazon_secret_key", String(40), nullable=True)
    amazon_ready_to_ship = Column("amazon_ready_to_ship", String(1), nullable=True)
    amazon_set_orders_downloaded = Column("amazon_set_orders_downloaded", String(1), nullable=True)
    bongo_checkout = Column("bongo_checkout", String(1), nullable=True)
    bongo_transfer = Column("bongo_transfer", String(15), nullable=True)
    bongo_partner_key = Column("bongo_partner_key", String(50), nullable=True)
    bongo_shipper = Column("bongo_shipper", String(100), nullable=True)
    bongo_dc_zip = Column("bongo_dc_zip", String(10), nullable=True)
    bongo_dc_state = Column("bongo_dc_state", String(2), nullable=True)
    bongo_dc_country = Column("bongo_dc_country", String(50), nullable=True)
    bongo_url = Column("bongo_url", String(100), nullable=True)
    bongo_exclude_countries = Column("bongo_exclude_countries", Text, nullable=True)
    bongo_cancel_notify = Column("bongo_cancel_notify", String(100), nullable=True)
    paypal_business = Column("paypal_business", String(100), nullable=True)
    paypal_skip = Column("paypal_skip", String(1), nullable=True)
    paypal_exp_username = Column("paypal_exp_username", String(50), nullable=True)
    paypal_exp_password = Column("paypal_exp_password", String(50), nullable=True)
    paypal_exp_signature = Column("paypal_exp_signature", String(255), nullable=True)
    paypal_exp_image = Column("paypal_exp_image", String(100), nullable=True)
    paypal_exp_billing = Column("paypal_exp_billing", String(1), nullable=True)
    paypal_exp_shipping = Column("paypal_exp_shipping", String(1), nullable=True)
    visa_checkout = Column("visa_checkout", String(1), nullable=True)
    visa_testing = Column("visa_testing", String(1), nullable=True)
    visa_merchant_id = Column("visa_merchant_id", String(100), nullable=True)
    visa_key = Column("visa_key", String(100), nullable=True)
    visa_share = Column("visa_share", String(100), nullable=True)
    visa_enckey = Column("visa_enckey", String(100), nullable=True)
    amazon_pay = Column("amazon_pay", String(1), nullable=False)
    amazon_client_id = Column("amazon_client_id", String(65), nullable=True)
    amazon_client_key = Column("amazon_client_key", String(65), nullable=True)
    amazon_pay_testing = Column("amazon_pay_testing", String(1), nullable=False)
    amazon_pay_test_declines = Column("amazon_pay_test_declines", String(1), nullable=False)
    paypal_exp_rest = Column("paypal_exp_rest", String(1), nullable=False)
    paypal_exp_authonly = Column("paypal_exp_authonly", String(1), nullable=False)
    paypal_exp_rest_environment = Column("paypal_exp_rest_environment", String(7), nullable=False)
    paypal_exp_rest_clientid = Column("paypal_exp_rest_clientid", String(80), nullable=True)
    paypal_exp_rest_secret = Column("paypal_exp_rest_secret", String(80), nullable=True)
    paypal_exp_rest_version = Column("paypal_exp_rest_version", String(1), nullable=True)
    paypal_use_shipping = Column("paypal_use_shipping", String(1), nullable=True)
    apple_pay = Column("apple_pay", String(1), nullable=True)
    apple_testing = Column("apple_testing", String(1), nullable=True)
    apple_testing_ips = Column("apple_testing_ips", Text, nullable=True)
    apple_merchant_id = Column("apple_merchant_id", String(40), nullable=True)
    apple_merchant_cert = Column("apple_merchant_cert", Text, nullable=True)
    apple_payment_cert = Column("apple_payment_cert", Text, nullable=True)
    sezzle = Column("sezzle", String(1), nullable=True)
    sezzle_testing = Column("sezzle_testing", String(1), nullable=True)
    sezzle_public_key = Column("sezzle_public_key", String(50), nullable=True)
    sezzle_private_key = Column("sezzle_private_key", String(50), nullable=True)
    paypal_unreachable = Column("paypal_unreachable", String(1), nullable=True)
    paypal_onboarded = Column("paypal_onboarded", String(1), nullable=True)
    paypal_exp_rest_merchant_id = Column("paypal_exp_rest_merchant_id", String(15), nullable=True)
    paypal_tracking_id = Column("paypal_tracking_id", Text, nullable=True)
