"""Auto-generated SQLAlchemy model for `display_options`.

Mirrors the colorcommerce.display_options table. Edit with care — re-running the
generator may overwrite changes.
"""
from sqlalchemy import Column, DateTime, Integer, String, Text
from app.database import Base


class DisplayOptions(Base):
    __tablename__ = "display_options"

    site_id = Column("site_id", Integer, primary_key=True)
    search_sort = Column("search_sort", String(12), nullable=True)
    search_sort_user_defined = Column("search_sort_user_defined", String(8), nullable=True)
    search_match_type = Column("search_match_type", String(12), nullable=True)
    search_prods = Column("search_prods", Text, nullable=True)
    search_fields = Column("search_fields", Text, nullable=True)
    search_ready = Column("search_ready", String(1), nullable=True)
    search_redirect_andor = Column("search_redirect_andor", String(3), nullable=True)
    search_limit_email_notify = Column("search_limit_email_notify", String(255), nullable=True)
    suppress_oos = Column("suppress_oos", String(1), nullable=True)
    use_suggested_search = Column("use_suggested_search", String(1), nullable=True)
    suggested_search_update = Column("suggested_search_update", String(7), nullable=True)
    suggested_search_num = Column("suggested_search_num", Integer, nullable=True)
    recipe_search_match_type = Column("recipe_search_match_type", String(12), nullable=True)
    use_category_filter = Column("use_category_filter", String(1), nullable=True)
    checkout_type = Column("checkout_type", String(1), nullable=True)
    product_mapping = Column("product_mapping", String(8), nullable=True)
    show_checkout_display = Column("show_checkout_display", String(1), nullable=True)
    checkout_quick_swap = Column("checkout_quick_swap", String(1), nullable=True)
    child_display_type = Column("child_display_type", String(1), nullable=True)
    additional_prod_display_type = Column("additional_prod_display_type", String(1), nullable=True)
    checkout_product_desc = Column("checkout_product_desc", String(11), nullable=True)
    hide_viewcart_discounts = Column("hide_viewcart_discounts", String(1), nullable=True)
    gift_msg_separate = Column("gift_msg_separate", String(1), nullable=True)
    gift_msg_num_lines = Column("gift_msg_num_lines", Integer, nullable=True)
    gift_msg_num_chars = Column("gift_msg_num_chars", Integer, nullable=True)
    checkout_vendor_ship = Column("checkout_vendor_ship", String(1), nullable=True)
    currency_type = Column("currency_type", String(7), nullable=True)
    not_found = Column("not_found", String(255), nullable=True)
    not_found_start = Column("not_found_start", DateTime, nullable=True)
    sitemap_invisible = Column("sitemap_invisible", String(1), nullable=True)
    sitemap_display = Column("sitemap_display", String(6), nullable=True)
    display_cgroups = Column("display_cgroups", String(1), nullable=True)
    featured_display = Column("featured_display", String(14), nullable=True)
    new_display = Column("new_display", String(14), nullable=True)
    specials_display = Column("specials_display", String(14), nullable=True)
    featured_cats_display = Column("featured_cats_display", String(14), nullable=True)
    featured_reviews_display = Column("featured_reviews_display", String(1), nullable=True)
    display_default_featured_prods = Column("display_default_featured_prods", String(1), nullable=True)
    upsells_prods = Column("upsells_prods", Text, nullable=True)
    best_sellers = Column("best_sellers", Text, nullable=True)
    best_sellers_display = Column("best_sellers_display", String(14), nullable=True)
    billing_type = Column("billing_type", String(255), nullable=True)
    bill_territories = Column("bill_territories", String(1), nullable=True)
    security_checkout_attempts = Column("security_checkout_attempts", Integer, nullable=True)
    security_terminate_session = Column("security_terminate_session", String(1), nullable=True)
    failed_cc_attempts_terminate_by = Column("failed_cc_attempts_terminate_by", String(7), nullable=True)
    failed_cc_attempts = Column("failed_cc_attempts", Integer, nullable=True)
    save_form = Column("save_form", String(1), nullable=True)
    save_forms = Column("save_forms", Text, nullable=True)
    simple_gateway_pages = Column("simple_gateway_pages", String(1), nullable=True)
    floating_cart = Column("floating_cart", String(1), nullable=True)
    redirect_handling = Column("redirect_handling", String(8), nullable=True)
    category_cfields = Column("category_cfields", Text, nullable=True)
    sitemap_linked = Column("sitemap_linked", String(1), nullable=True)
    page_caching = Column("page_caching", String(1), nullable=False)
    page_caching_duration = Column("page_caching_duration", Integer, nullable=False)
    page_caching_minify = Column("page_caching_minify", String(1), nullable=False)
    cart_updates_data_available = Column("cart_updates_data_available", String(1), nullable=True)
    display_hidden_prods = Column("display_hidden_prods", Text, nullable=True)
    display_hidden_prods_cats = Column("display_hidden_prods_cats", Text, nullable=True)
    persistent_guest_cart = Column("persistent_guest_cart", String(1), nullable=True)
    currency_type_cad = Column("currency_type_cad", String(1), nullable=True)
    overdrive_enable = Column("overdrive_enable", String(1), nullable=True)
    overdrive_settings = Column("overdrive_settings", Text, nullable=True)
    isolated_cc_collect_live = Column("isolated_cc_collect_live", String(1), nullable=False)
    isolated_cc_collect_staging = Column("isolated_cc_collect_staging", String(1), nullable=False)
