"""Auto-generated SQLAlchemy model for `google_base`.

Mirrors the colorcommerce.google_base table. Edit with care — re-running the
generator may overwrite changes.
"""
from sqlalchemy import Column, Date, DateTime, Integer, String, Text
from app.database import Base


class GoogleBase(Base):
    __tablename__ = "google_base"

    site_id = Column("site_id", Integer, primary_key=True)
    feed_title = Column("feed_title", String(100), nullable=True)
    feed_description = Column("feed_description", String(250), nullable=True)
    feed_expiration = Column("feed_expiration", Date, nullable=True)
    title = Column("title", String(50), nullable=True)
    description = Column("description", String(50), nullable=True)
    brand = Column("brand", String(50), nullable=True)
    brand_global_text = Column("brand_global_text", String(50), nullable=True)
    product_type = Column("product_type", String(50), nullable=True)
    department = Column("department", String(50), nullable=True)
    mpn = Column("mpn", String(50), nullable=True)
    modelno = Column("modelno", String(50), nullable=True)
    gtin = Column("gtin", String(50), nullable=True)
    payment_accepted = Column("payment_accepted", String(100), nullable=True)
    payment_notes = Column("payment_notes", String(100), nullable=True)
    url_append_value = Column("url_append_value", String(100), nullable=True)
    url_subprod = Column("url_subprod", String(1), nullable=True)
    special_prices = Column("special_prices", String(1), nullable=True)
    products = Column("products", Text, nullable=True)
    excl_products = Column("excl_products", Text, nullable=True)
    excl_content_prods = Column("excl_content_prods", String(1), nullable=True)
    current_files = Column("current_files", Text, nullable=True)
    last_export = Column("last_export", DateTime, nullable=True)
    email = Column("email", String(50), nullable=True)
    size = Column("size", String(11), nullable=True)
    size_match = Column("size_match", String(50), nullable=True)
    color = Column("color", String(11), nullable=True)
    color_match = Column("color_match", String(50), nullable=True)
    pattern = Column("pattern", String(11), nullable=True)
    pattern_match = Column("pattern_match", String(50), nullable=True)
    material = Column("material", String(11), nullable=True)
    material_match = Column("material_match", String(50), nullable=True)
    shipping_length = Column("shipping_length", String(15), nullable=True)
    shipping_width = Column("shipping_width", String(15), nullable=True)
    shipping_height = Column("shipping_height", String(15), nullable=True)
    pcondition = Column("pcondition", String(11), nullable=True)
    item_group_id = Column("item_group_id", String(50), nullable=True)
    child_image = Column("child_image", String(1), nullable=True)
    hide_blank = Column("hide_blank", String(1), nullable=True)
    ship_price = Column("ship_price", String(11), nullable=True)
    age_group = Column("age_group", String(10), nullable=True)
    age_group_field = Column("age_group_field", String(7), nullable=True)
    gender = Column("gender", String(6), nullable=True)
    gender_field = Column("gender_field", String(7), nullable=True)
    availability = Column("availability", String(20), nullable=True)
    availability_field = Column("availability_field", String(7), nullable=True)
    google_category = Column("google_category", String(50), nullable=True)
    include_tax = Column("include_tax", String(1), nullable=False)
    output_file = Column("output_file", String(3), nullable=True)
    auto_feed = Column("auto_feed", String(1), nullable=False)
    auto_file_name = Column("auto_file_name", String(10), nullable=False)
    separate_atty = Column("separate_atty", String(1), nullable=True)
    separate_atty_price = Column("separate_atty_price", String(50), nullable=True)
    adwords_group = Column("adwords_group", String(50), nullable=True)
    adwords_labels = Column("adwords_labels", String(50), nullable=True)
    adwords_redirect = Column("adwords_redirect", String(50), nullable=True)
    custom_label_name = Column("custom_label_name", String(255), nullable=True)
    custom_label_0 = Column("custom_label_0", String(50), nullable=True)
    custom_label_1 = Column("custom_label_1", String(50), nullable=True)
    custom_label_2 = Column("custom_label_2", String(50), nullable=True)
    custom_label_3 = Column("custom_label_3", String(50), nullable=True)
    custom_label_4 = Column("custom_label_4", String(50), nullable=True)
    truncate_fields = Column("truncate_fields", String(1), nullable=True)
    strip_html = Column("strip_html", String(1), nullable=True)
    use_attribute_custom_fields = Column("use_attribute_custom_fields", String(1), nullable=True)
    categories = Column("categories", Text, nullable=True)
    excl_categories = Column("excl_categories", Text, nullable=True)
    excl_no_cat = Column("excl_no_cat", String(1), nullable=True)
    cust_filter_field = Column("cust_filter_field", String(10), nullable=True)
    cust_filter_contents = Column("cust_filter_contents", Text, nullable=True)
    exclude_out_of_season = Column("exclude_out_of_season", String(1), nullable=True)
