"""Auto-generated SQLAlchemy model for `marketing_options`.

Mirrors the colorcommerce.marketing_options table. Edit with care — re-running the
generator may overwrite changes.
"""
from sqlalchemy import Column, Integer, Numeric, String, Text
from app.database import Base


class MarketingOptions(Base):
    __tablename__ = "marketing_options"

    site_id = Column("site_id", Integer, primary_key=True)
    hubspot_leads = Column("hubspot_leads", String(1), nullable=True)
    hubspot_apikey = Column("hubspot_apikey", String(100), nullable=True)
    hubspot_portalid = Column("hubspot_portalid", String(100), nullable=True)
    hubspot_createform_guid = Column("hubspot_createform_guid", String(100), nullable=True)
    hubspot_skus = Column("hubspot_skus", String(1), nullable=True)
    bronto_token = Column("bronto_token", String(50), nullable=True)
    bronto_abandon = Column("bronto_abandon", String(1), nullable=True)
    bronto_order = Column("bronto_order", String(1), nullable=True)
    bronto_order_message = Column("bronto_order_message", String(50), nullable=True)
    bronto_send_order = Column("bronto_send_order", String(1), nullable=True)
    bronto_whensend_orders = Column("bronto_whensend_orders", String(8), nullable=True)
    bronto_contacts = Column("bronto_contacts", String(1), nullable=True)
    bronto_contacts_typ = Column("bronto_contacts_typ", String(100), nullable=True)
    bronto_contacts_eml = Column("bronto_contacts_eml", String(100), nullable=True)
    bronto_contacts_lst = Column("bronto_contacts_lst", String(100), nullable=True)
    bronto_contacts_sid = Column("bronto_contacts_sid", String(10), nullable=True)
    bronto_contacts_uid = Column("bronto_contacts_uid", String(10), nullable=True)
    bronto_contacts_key = Column("bronto_contacts_key", String(50), nullable=True)
    rejoiner_enable = Column("rejoiner_enable", String(1), nullable=False)
    rejoiner_site_id = Column("rejoiner_site_id", String(50), nullable=False)
    rejoiner_api_key = Column("rejoiner_api_key", String(50), nullable=False)
    rejoiner_api_secret = Column("rejoiner_api_secret", String(50), nullable=False)
    mailchimp_enable = Column("mailchimp_enable", String(1), nullable=False)
    mailchimp_second_prod_push = Column("mailchimp_second_prod_push", String(1), nullable=True)
    mailchimp_api_key = Column("mailchimp_api_key", String(50), nullable=True)
    mailchimp_list_id = Column("mailchimp_list_id", String(100), nullable=True)
    uri_redirects_case_insensitive = Column("uri_redirects_case_insensitive", String(1), nullable=False)
    mailchimp_order = Column("mailchimp_order", String(1), nullable=True)
    dotmailer_enable = Column("dotmailer_enable", String(1), nullable=True)
    dotmailer_endpoint = Column("dotmailer_endpoint", String(50), nullable=True)
    dotmailer_username = Column("dotmailer_username", String(50), nullable=True)
    dotmailer_password = Column("dotmailer_password", String(50), nullable=True)
    dotmailer_carts = Column("dotmailer_carts", String(255), nullable=True)
    dotmailer_orders = Column("dotmailer_orders", String(255), nullable=True)
    dotmailer_js = Column("dotmailer_js", String(1), nullable=True)
    dotmailer_insight_id = Column("dotmailer_insight_id", String(50), nullable=True)
    dotmailer_program_id = Column("dotmailer_program_id", String(50), nullable=True)
    dotmailer_cart_delay = Column("dotmailer_cart_delay", Integer, nullable=True)
    google_sitemap_auto = Column("google_sitemap_auto", String(1), nullable=True)
    google_sitemap_email = Column("google_sitemap_email", String(50), nullable=True)
    bronto_rest_api_id = Column("bronto_rest_api_id", String(50), nullable=True)
    bronto_rest_api_secret = Column("bronto_rest_api_secret", String(50), nullable=True)
    structured_data_logo = Column("structured_data_logo", String(25), nullable=True)
    structured_data_phone = Column("structured_data_phone", String(25), nullable=True)
    structured_data_address1 = Column("structured_data_address1", String(25), nullable=True)
    structured_data_address2 = Column("structured_data_address2", String(25), nullable=True)
    structured_data_city = Column("structured_data_city", String(25), nullable=True)
    structured_data_state = Column("structured_data_state", String(25), nullable=True)
    structured_data_country = Column("structured_data_country", String(25), nullable=True)
    structured_data_zip = Column("structured_data_zip", String(25), nullable=True)
    structured_data_lat = Column("structured_data_lat", Numeric(13, 10), nullable=True)
    structured_data_long = Column("structured_data_long", Numeric(13, 10), nullable=True)
    structured_data_phone_local = Column("structured_data_phone_local", String(25), nullable=True)
    structured_data_hours = Column("structured_data_hours", Text, nullable=True)
    structured_data_social = Column("structured_data_social", Text, nullable=True)
    email_app_store_use = Column("email_app_store_use", String(1), nullable=True)
    email_app_store_config_id = Column("email_app_store_config_id", Integer, nullable=True)
    email_app_store_config = Column("email_app_store_config", Text, nullable=True)
    klaviyo_enabled = Column("klaviyo_enabled", String(1), nullable=True)
    klaviyo_api_key = Column("klaviyo_api_key", String(255), nullable=True)
    klaviyo_private_api_key = Column("klaviyo_private_api_key", String(255), nullable=True)
    klaviyo_list_id = Column("klaviyo_list_id", String(255), nullable=True)
    klaviyo_track_viewed_product = Column("klaviyo_track_viewed_product", String(1), nullable=True)
    klaviyo_track_added_to_cart = Column("klaviyo_track_added_to_cart", String(1), nullable=True)
    klaviyo_track_started_checkout = Column("klaviyo_track_started_checkout", String(1), nullable=True)
    klaviyo_track_ordered_product = Column("klaviyo_track_ordered_product", String(1), nullable=True)
