"""Auto-generated SQLAlchemy model for `order_management`.

Mirrors the colorcommerce.order_management table. Edit with care — re-running the
generator may overwrite changes.
"""
from sqlalchemy import Column, DateTime, Float, Integer, String
from app.database import Base


class OrderManagement(Base):
    __tablename__ = "order_management"

    site_id = Column("site_id", Integer, primary_key=True)
    order_management = Column("order_management", String(12), nullable=True)
    aero_client_id = Column("aero_client_id", String(25), nullable=True)
    aero_order_prefix = Column("aero_order_prefix", String(10), nullable=True)
    aero_error_email = Column("aero_error_email", String(255), nullable=True)
    aero_paypalexp_copyshipbill = Column("aero_paypalexp_copyshipbill", String(1), nullable=True)
    mom_giftwrap_sku = Column("mom_giftwrap_sku", String(50), nullable=True)
    mom_prod_import_subprods = Column("mom_prod_import_subprods", String(1), nullable=True)
    mom_xml_gift_location = Column("mom_xml_gift_location", String(8), nullable=True)
    mom_xml_ctype1 = Column("mom_xml_ctype1", String(50), nullable=True)
    mom_xml_ordertype = Column("mom_xml_ordertype", String(50), nullable=True)
    mom_xml_sales_id = Column("mom_xml_sales_id", String(50), nullable=True)
    mom_xml_inpart = Column("mom_xml_inpart", String(50), nullable=True)
    mom_xml_oper_id = Column("mom_xml_oper_id", String(50), nullable=True)
    mom_xml_cat_source = Column("mom_xml_cat_source", String(50), nullable=True)
    se_coupon = Column("se_coupon", String(1), nullable=True)
    se_discount = Column("se_discount", String(1), nullable=True)
    se_user_id = Column("se_user_id", String(1), nullable=True)
    se_custnum_webcustid = Column("se_custnum_webcustid", String(1), nullable=True)
    se_paypalexp_copyshipbill = Column("se_paypalexp_copyshipbill", String(1), nullable=True)
    se_product_sort = Column("se_product_sort", String(10), nullable=True)
    in_auto_download = Column("in_auto_download", String(1), nullable=True)
    in_db_user = Column("in_db_user", String(20), nullable=True)
    in_db_host = Column("in_db_host", String(50), nullable=True)
    in_db_name = Column("in_db_name", String(20), nullable=True)
    in_db_pass = Column("in_db_pass", String(20), nullable=True)
    in_db_port = Column("in_db_port", String(10), nullable=True)
    in_owner_code = Column("in_owner_code", String(10), nullable=True)
    in_order_class = Column("in_order_class", String(20), nullable=True)
    in_campaign_code = Column("in_campaign_code", String(20), nullable=True)
    in_st_ip = Column("in_st_ip", String(20), nullable=True)
    in_st_port = Column("in_st_port", String(10), nullable=True)
    in_auto_inventory = Column("in_auto_inventory", String(1), nullable=True)
    in_catalog_request = Column("in_catalog_request", String(1), nullable=True)
    in_gc_processor = Column("in_gc_processor", String(1), nullable=True)
    in_order_tracking = Column("in_order_tracking", String(1), nullable=True)
    cms_import = Column("cms_import", String(9), nullable=True)
    cms_lineitem = Column("cms_lineitem", String(8), nullable=True)
    cms_ord_prefix = Column("cms_ord_prefix", String(50), nullable=True)
    cms_tax_insure = Column("cms_tax_insure", String(1), nullable=True)
    cms_use_att_sku = Column("cms_use_att_sku", String(1), nullable=True)
    cms_paypalexp_copyshipbill = Column("cms_paypalexp_copyshipbill", String(1), nullable=True)
    om_auto_download = Column("om_auto_download", String(1), nullable=True)
    om_auto_inventory = Column("om_auto_inventory", String(1), nullable=True)
    om_auto_shipping = Column("om_auto_shipping", String(1), nullable=True)
    om_auto_shipping_history = Column("om_auto_shipping_history", String(1), nullable=True)
    om_last_shipping_history = Column("om_last_shipping_history", DateTime, nullable=True)
    om_keycode = Column("om_keycode", String(50), nullable=True)
    om_cat_keycode = Column("om_cat_keycode", String(50), nullable=True)
    om_use_cat_source = Column("om_use_cat_source", String(1), nullable=True)
    om_sourcetokeycode = Column("om_sourcetokeycode", String(1), nullable=True)
    om_promotosource = Column("om_promotosource", String(1), nullable=True)
    om_version = Column("om_version", Float, nullable=True)
    om_store_code = Column("om_store_code", String(5), nullable=True)
    om_pin = Column("om_pin", String(50), nullable=True)
    om_dob = Column("om_dob", String(1), nullable=True)
    om_httpbizid = Column("om_httpbizid", String(255), nullable=True)
    om_paymentech_pad = Column("om_paymentech_pad", String(1), nullable=True)
    om_gc_processor = Column("om_gc_processor", String(1), nullable=True)
    om_paypalexp_copyshipbill = Column("om_paypalexp_copyshipbill", String(1), nullable=True)
    sp_auto_download = Column("sp_auto_download", String(1), nullable=True)
    sp_auto_tracking = Column("sp_auto_tracking", String(1), nullable=True)
    sp_service_location = Column("sp_service_location", String(100), nullable=True)
    sp_paypalexp_copyshipbill = Column("sp_paypalexp_copyshipbill", String(1), nullable=True)
    vi_auto_download = Column("vi_auto_download", String(1), nullable=True)
    vi_web_id = Column("vi_web_id", String(50), nullable=True)
    vi_identifier = Column("vi_identifier", String(50), nullable=True)
    vi_error_email = Column("vi_error_email", String(255), nullable=True)
    vi_environment = Column("vi_environment", String(10), nullable=True)
    vi_paypalexp_copyshipbill = Column("vi_paypalexp_copyshipbill", String(1), nullable=True)
    custom_url = Column("custom_url", String(50), nullable=True)
    custom_auto_download = Column("custom_auto_download", String(1), nullable=False)
    custom_keyname = Column("custom_keyname", String(30), nullable=True)
    custom_apikey = Column("custom_apikey", String(30), nullable=True)
    custom_protocol = Column("custom_protocol", String(5), nullable=False)
    custom_format = Column("custom_format", String(4), nullable=True)
    custom_live = Column("custom_live", String(1), nullable=True)
    custom_inventory_updates = Column("custom_inventory_updates", String(1), nullable=True)
    custom_catalog_requests = Column("custom_catalog_requests", String(1), nullable=True)
    custom_auto_shipping_history = Column("custom_auto_shipping_history", String(1), nullable=True)
    custom_last_shipping_history = Column("custom_last_shipping_history", DateTime, nullable=True)
    mom_builder_delimiter = Column("mom_builder_delimiter", String(1), nullable=True)
    mom_builder_five_prods = Column("mom_builder_five_prods", String(1), nullable=False)
    mom_builder_qualifier = Column("mom_builder_qualifier", String(1), nullable=False)
    mom_builder_gift_cert_lineitem = Column("mom_builder_gift_cert_lineitem", String(1), nullable=True)
    mom_builder_file_extension = Column("mom_builder_file_extension", String(3), nullable=True)
