"""Auto-generated SQLAlchemy model for `order_options`.

Mirrors the colorcommerce.order_options table. Edit with care — re-running the
generator may overwrite changes.
"""
from sqlalchemy import Column, Float, Integer, String, Text
from app.database import Base


class OrderOptions(Base):
    __tablename__ = "order_options"

    site_id = Column("site_id", Integer, primary_key=True)
    fractional_qty = Column("fractional_qty", String(1), nullable=True)
    encrypt_orders = Column("encrypt_orders", String(1), nullable=True)
    encrypt_orders_status = Column("encrypt_orders_status", String(8), nullable=True)
    email_conf_customers = Column("email_conf_customers", String(1), nullable=True)
    email_conf_bcc = Column("email_conf_bcc", String(255), nullable=True)
    email_vendor_bcc = Column("email_vendor_bcc", String(255), nullable=True)
    email_conf_storeowner = Column("email_conf_storeowner", String(1), nullable=True)
    tracking_notify = Column("tracking_notify", String(1), nullable=True)
    tracking_notify_subject = Column("tracking_notify_subject", String(255), nullable=True)
    tracking_notify_from = Column("tracking_notify_from", String(255), nullable=True)
    tracking_notify_bcc = Column("tracking_notify_bcc", String(255), nullable=True)
    pdf_cust = Column("pdf_cust", Text, nullable=True)
    pdf_order_prefix = Column("pdf_order_prefix", String(20), nullable=True)
    orderpdf_print_ccnum = Column("orderpdf_print_ccnum", String(1), nullable=True)
    member_approve = Column("member_approve", String(1), nullable=True)
    member_approve_from = Column("member_approve_from", String(255), nullable=True)
    member_change_notify = Column("member_change_notify", String(1), nullable=True)
    member_change_notify_email = Column("member_change_notify_email", String(150), nullable=True)
    member_change_notify_subject = Column("member_change_notify_subject", String(150), nullable=True)
    member_approve_to = Column("member_approve_to", String(255), nullable=True)
    member_birthday_email = Column("member_birthday_email", String(1), nullable=True)
    member_birthday_from_email = Column("member_birthday_from_email", String(100), nullable=True)
    member_birthday_subject = Column("member_birthday_subject", String(255), nullable=True)
    member_cart_clear_confirm = Column("member_cart_clear_confirm", String(1), nullable=True)
    member_wishlist_require_zip = Column("member_wishlist_require_zip", String(1), nullable=True)
    member_incentive_login = Column("member_incentive_login", String(1), nullable=True)
    member_email_conf = Column("member_email_conf", String(1), nullable=True)
    wholesale_cart_expire = Column("wholesale_cart_expire", Integer, nullable=True)
    reminder_service_from = Column("reminder_service_from", String(255), nullable=True)
    reminder_service_subject = Column("reminder_service_subject", String(255), nullable=True)
    gift_certificate_delay = Column("gift_certificate_delay", String(1), nullable=True)
    gift_certificate_fee_amount = Column("gift_certificate_fee_amount", Float, nullable=True)
    gift_certificate_fee_type = Column("gift_certificate_fee_type", String(1), nullable=True)
    gift_certificate_applyshipping = Column("gift_certificate_applyshipping", String(1), nullable=True)
    gift_certificate_applytax = Column("gift_certificate_applytax", String(1), nullable=True)
    gift_certificate_applypromos = Column("gift_certificate_applypromos", String(1), nullable=True)
    orderpdf_print_ccinfo = Column("orderpdf_print_ccinfo", String(1), nullable=True)
    orderpdf_separate_shiptos = Column("orderpdf_separate_shiptos", String(1), nullable=True)
    sift_science = Column("sift_science", String(1), nullable=True)
    sift_science_apikey = Column("sift_science_apikey", String(100), nullable=True)
    sift_science_blockid = Column("sift_science_blockid", String(100), nullable=True)
    sift_science_allowid = Column("sift_science_allowid", String(100), nullable=True)
    custom_member_api = Column("custom_member_api", String(1), nullable=True)
    custom_member_api_url = Column("custom_member_api_url", String(50), nullable=True)
    custom_member_api_key = Column("custom_member_api_key", String(50), nullable=True)
    custom_member_api_keyid = Column("custom_member_api_keyid", String(50), nullable=True)
    custom_member_api_protocol = Column("custom_member_api_protocol", String(5), nullable=True)
    custom_member_api_format = Column("custom_member_api_format", String(4), nullable=True)
    custom_member_api_wishlist = Column("custom_member_api_wishlist", String(1), nullable=True)
    custom_member_api_cart = Column("custom_member_api_cart", String(1), nullable=True)
    recurring_orders_by_product = Column("recurring_orders_by_product", String(1), nullable=True)
    sift_version = Column("sift_version", String(3), nullable=True)
    sift_payment_abuse_acceptid = Column("sift_payment_abuse_acceptid", Text, nullable=True)
    sift_account_abuse_acceptid = Column("sift_account_abuse_acceptid", Text, nullable=True)
    sift_content_abuse_acceptid = Column("sift_content_abuse_acceptid", Text, nullable=True)
    sift_promotion_abuse_acceptid = Column("sift_promotion_abuse_acceptid", Text, nullable=True)
    member_persistent_cart = Column("member_persistent_cart", String(1), nullable=False)
    member_persistent_cart_exclude_promos = Column("member_persistent_cart_exclude_promos", String(1), nullable=True)
    gift_certificate_internal_external = Column("gift_certificate_internal_external", String(1), nullable=True)
    gift_certificate_internal_name = Column("gift_certificate_internal_name", String(40), nullable=True)
    gift_certificate_external_name = Column("gift_certificate_external_name", String(40), nullable=True)
    member_required_fields = Column("member_required_fields", Text, nullable=True)
    fraud_app_store_use = Column("fraud_app_store_use", String(1), nullable=True)
    fraud_app_store_config_id = Column("fraud_app_store_config_id", Integer, nullable=True)
    fraud_app_store_config = Column("fraud_app_store_config", Text, nullable=True)
    more_member_email_alerts = Column("more_member_email_alerts", String(1), nullable=True)
