"""Auto-generated SQLAlchemy model for `shipping_rate_tool`.

Mirrors the colorcommerce.shipping_rate_tool table. Edit with care — re-running the
generator may overwrite changes.
"""
from sqlalchemy import Column, Float, Integer, String
from app.database import Base


class ShippingRateTool(Base):
    __tablename__ = "shipping_rate_tool"

    site_id = Column("site_id", Integer, primary_key=True)
    rate_calc = Column("rate_calc", String(1), nullable=True)
    ship_from_zip = Column("ship_from_zip", String(10), nullable=True)
    calc_type = Column("calc_type", String(10), nullable=True)
    num_per_box = Column("num_per_box", Integer, nullable=True)
    ship_type = Column("ship_type", String(1), nullable=True)
    min_ups = Column("min_ups", Float, nullable=True)
    ups_rate_type = Column("ups_rate_type", String(10), nullable=True)
    ups_time_in_transit = Column("ups_time_in_transit", String(1), nullable=True)
    ups_transit_fixed = Column("ups_transit_fixed", String(1), nullable=True)
    ups_freight_user = Column("ups_freight_user", String(25), nullable=True)
    ups_freight_password = Column("ups_freight_password", String(25), nullable=True)
    ups_freight_access_key = Column("ups_freight_access_key", String(16), nullable=True)
    ups_freight_ship_num = Column("ups_freight_ship_num", String(255), nullable=True)
    fedex_rate_calc = Column("fedex_rate_calc", String(1), nullable=True)
    fedex_server = Column("fedex_server", String(4), nullable=True)
    fedex_account_num = Column("fedex_account_num", String(20), nullable=True)
    fedex_meter_num = Column("fedex_meter_num", String(20), nullable=True)
    fedex_from_state = Column("fedex_from_state", String(10), nullable=True)
    fedex_ship_from_zip = Column("fedex_ship_from_zip", String(10), nullable=True)
    fedex_from_country = Column("fedex_from_country", String(10), nullable=True)
    fedex_min = Column("fedex_min", Float, nullable=True)
    fedex_calc_type = Column("fedex_calc_type", String(5), nullable=True)
    fedex_num_per_box = Column("fedex_num_per_box", Integer, nullable=True)
    fedex_ship_type = Column("fedex_ship_type", String(1), nullable=True)
    fedex_valadd = Column("fedex_valadd", String(1), nullable=True)
    fedex_calc_version = Column("fedex_calc_version", String(1), nullable=True)
    fedex_account_key = Column("fedex_account_key", String(32), nullable=True)
    fedex_account_pass = Column("fedex_account_pass", String(128), nullable=True)
    fedex_discount_to_net = Column("fedex_discount_to_net", String(1), nullable=True)
    fedex_freight_account_num = Column("fedex_freight_account_num", String(20), nullable=True)
    fedex_freight_address = Column("fedex_freight_address", String(100), nullable=True)
    fedex_freight_address2 = Column("fedex_freight_address2", String(100), nullable=True)
    fedex_freight_city = Column("fedex_freight_city", String(20), nullable=True)
    fedex_freight_state = Column("fedex_freight_state", String(20), nullable=True)
    fedex_freight_country = Column("fedex_freight_country", String(20), nullable=True)
    fedex_freight_zip = Column("fedex_freight_zip", String(20), nullable=True)
    fedex_freight_from = Column("fedex_freight_from", String(11), nullable=True)
    usps_rate_calc = Column("usps_rate_calc", String(1), nullable=True)
    usps_user_id = Column("usps_user_id", String(20), nullable=True)
    usps_live = Column("usps_live", String(1), nullable=True)
    usps_ship_from_zip = Column("usps_ship_from_zip", String(10), nullable=True)
    usps_calc_type = Column("usps_calc_type", String(5), nullable=True)
    usps_num_per_box = Column("usps_num_per_box", Integer, nullable=True)
    usps_min = Column("usps_min", Float, nullable=True)
    abf_rate_calc = Column("abf_rate_calc", String(1), nullable=True)
    abf_acct_num = Column("abf_acct_num", String(10), nullable=True)
    abf_pass = Column("abf_pass", String(10), nullable=True)
    abf_from_city = Column("abf_from_city", String(100), nullable=True)
    abf_from_state = Column("abf_from_state", String(100), nullable=True)
    abf_from_zip = Column("abf_from_zip", String(10), nullable=True)
    abf_from_country = Column("abf_from_country", String(100), nullable=True)
    abf_min = Column("abf_min", Float, nullable=True)
    cw_rate_calc = Column("cw_rate_calc", String(1), nullable=True)
    cw_pass = Column("cw_pass", String(50), nullable=True)
    cw_user = Column("cw_user", String(50), nullable=True)
    cw_customer_num = Column("cw_customer_num", String(50), nullable=True)
    cw_from_zip = Column("cw_from_zip", String(15), nullable=True)
    cw_from_country = Column("cw_from_country", String(100), nullable=True)
    cw_min = Column("cw_min", Float, nullable=True)
    api_calc = Column("api_calc", String(1), nullable=True)
    ship_url = Column("ship_url", String(255), nullable=True)
    ship_post_type = Column("ship_post_type", String(4), nullable=True)
    custom_shipping_api_version = Column("custom_shipping_api_version", String(1), nullable=True)
    custom_shipping_api_username = Column("custom_shipping_api_username", String(65), nullable=True)
    custom_shipping_api_password = Column("custom_shipping_api_password", String(65), nullable=True)
    custom_shipping_api_key = Column("custom_shipping_api_key", String(65), nullable=True)
    fedex_transit_time = Column("fedex_transit_time", String(1), nullable=True)
    ups_freight_client_id = Column("ups_freight_client_id", String(255), nullable=True)
    ups_freight_client_secret = Column("ups_freight_client_secret", String(255), nullable=True)
    ups_freight_default_auth = Column("ups_freight_default_auth", String(5), nullable=True)
    fedex_rest_client_id = Column("fedex_rest_client_id", String(255), nullable=True)
    fedex_rest_client_secret = Column("fedex_rest_client_secret", String(255), nullable=True)
    fedex_rest_default_auth = Column("fedex_rest_default_auth", String(255), nullable=True)
    use_for_tax_calc = Column("use_for_tax_calc", String(1), nullable=True)
    excl_address = Column("excl_address", String(1), nullable=True)
